"""Add created field to Post

Revision ID: e3b371744207
Revises: d8d2655425a3
Create Date: 2020-07-10 21:48:29.311030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b371744207'
down_revision = 'd8d2655425a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created')
    # ### end Alembic commands ###
